### ISSUE TITLE
Parse laterality when converting DICOM SEG to NRRD

### ISSUE THREAD

**Issue by denbonte** [ImagingDataCommons/ai_medima_misc#1]
In the `dicomseg_to_nrrd` function in https://github.com/ImagingDataCommons/ai_medima_misc/blob/main/nnunet/src/utils/postprocessing.py -- in the renaming of the labels from integers to the SegmentLabels, there could be cases where this fails. 

That is, cases where there are multiple instances of the same SegmentLabel (e.g. Lung) but then the laterality is different.

**Comment by fedorov** [comment]
This issue is no longer relevant to the current content of the repository.
